language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs"
notifications:
  email: false
  slack:
    secure: EdfFKXJfmrqtzs38Z1qar3OyiNXzi5y/MCj9LcI5V9Gnqk6sRpn8l/KH5Vfbdg7LplvLO4DO+QLy6FzEoowmGsD7WuGn7HicaBGy8MKrIHLmDm9lripDVPd3gG8lwrZENcAmIerRnE3P1GbrjuvbCr0JlEIMT8tqhCxEeRNkdb/rZ+b70/rJPy26fGZWXcHLkg1hjI93KT9DP6t8+K7pDDayzTlpssJQduRmurnfHOKPCn6KyCtYerXyqewQhPhz7MZY+d+m1xCAxM75QMR9jlbQqb1dHeH+zgiHJB/y8/BIiGF33HKa/AjJiwiwfqXv8EJ4brGbBl5S8gypQn9huQ3+WTQFya8l9TDYTzPiCtVQwAFUWnUIXWFrQkFc6utcmQhe4ghOBcTGR8e0JWWaC7WooCCIw/cYRyBsUcRWIydG0OnDv5TZgewo6ZkIwsYFcGXhQZxklzfhj0UhGf+yLE1K/Hm6hkAKY6fJdcOgvHKNKQcaT8qpDHbsitSmJWq0Q88EjmWjlhRxcJ0MGB9dYPsQ2pS/QZWbuzSbHGCxFpGySyiKr4OfjNjDxnVnvS8qXToUOwZTy3pWoW+pS2MN2v3MXXzBGzxtK/PYAPQxVIrmWaf46CG8b7c3bMyp4SP8qRAElPjVrmaPwu2OkUWYGJ3GyGOXLipzQH1ikl6eAO8=
